# Copyright (c) Jupyter Accessibility Team.
# Distributed under the terms of the Modified BSD License.

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx docs/"
      - echo "Sphinx configuration sucessfully created"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  fail_on_warning: false
  configuration: docs/conf.py
