#!/usr/bin/env bash
set -eux
doit list --all --status

mkdir -p logs

time doit clone |& tee logs/00.clone.log
time doit setup |& tee logs/01.setup.log
time doit link  |& tee logs/02.link.log
time doit app   |& tee logs/03.app.log

doit list --all --status
